version: '3.8'

services:
  frontend:
    build: .
    env_file: ".env"
    networks:
      - proxy
    restart: always
    ports:
      - 8000:8000
networks:
  proxy:
    external: true
    name: "8651f5efd1b17dbd02faad559c12fa3d36bdae18d720c4de3b6cf6627db9cec6_proxy"
