// THIS FILE IS AUTOMATICALLY GENERATED!
// See: runscripts/extract-routes.js

/* eslint-disable */
export const ROUTES = {
  "COMPONENT_LIBRARY_HOME": {
    "name": "COMPONENT_LIBRARY_HOME",
    "path": "/component-library/",
    "title": "Component Library",
    "shortTitle": "Home"
  },
  "COMPONENT_LIBRARY_PRESENTATIONAL_ATOMS": {
    "name": "COMPONENT_LIBRARY_PRESENTATIONAL_ATOMS",
    "path": "/component-library/presentational-atoms/",
    "title": "Component Library | Presentational: Atoms",
    "shortTitle": "Atoms"
  },
  "COMPONENT_LIBRARY_PRESENTATIONAL_MOLECULES": {
    "name": "COMPONENT_LIBRARY_PRESENTATIONAL_MOLECULES",
    "path": "/component-library/presentational-molecules/",
    "title": "Component Library | Presentational: Molecules",
    "shortTitle": "Molecules"
  },
  "COMPONENT_LIBRARY_PRESENTATIONAL_ORGANISMS": {
    "name": "COMPONENT_LIBRARY_PRESENTATIONAL_ORGANISMS",
    "path": "/component-library/presentational-organisms/",
    "title": "Component Library | Presentational: Organisms",
    "shortTitle": "Organisms"
  },
  "COMPONENT_LIBRARY_CONTAINER_GENERAL": {
    "name": "COMPONENT_LIBRARY_CONTAINER_GENERAL",
    "path": "/component-library/container-general/",
    "title": "Component Library | Container: General",
    "shortTitle": "General"
  },
  "COMPONENT_LIBRARY_CONTAINER_USER": {
    "name": "COMPONENT_LIBRARY_CONTAINER_USER",
    "path": "/component-library/container-user/",
    "title": "Component Library | Container: User",
    "shortTitle": "User"
  },
  "BRAIN_MAP_MANAGER": {
    "name": "BRAIN_MAP_MANAGER",
    "path": "/brain-map-manager/",
    "title": "Brain Map Manager"
  },
  "BRAIN_MAP_UPLOAD": {
    "name": "BRAIN_MAP_UPLOAD",
    "path": "/brain-map-upload/:stepSlug?/",
    "title": "Brain Map Upload"
  },
  "BRAIN_MAP_VIEWER": {
    "name": "BRAIN_MAP_VIEWER",
    "path": "/brain-map-viewer/:slug/",
    "title": "Brain Map Viewer",
    "exampleParam": {
      "slug": "comparing-quality-gbm-l"
    }
  },
  "BRAIN_MAP_VIEWER_ID": {
    "name": "BRAIN_MAP_VIEWER_ID",
    "path": "/brain-map-viewer/:id/",
    "title": "Brain Map Viewer"
  },
  "GENERAL_APP_DIRECTORY": {
    "name": "GENERAL_APP_DIRECTORY",
    "path": "/",
    "title": "App Directory"
  },
  "ERROR_PAGE": {
    "name": "ERROR_PAGE",
    "path": "*",
    "title": "Error Page"
  },
  "RESEARCH_BRAIN_MAP_MANAGER": {
    "name": "RESEARCH_BRAIN_MAP_MANAGER",
    "path": "/research-brain-map-manager/",
    "title": "Research Brain Maps"
  },
  "USER_SIGN_UP": {
    "name": "USER_SIGN_UP",
    "path": "/sign-up/"
  },
  "USER_LOG_IN": {
    "name": "USER_LOG_IN",
    "path": "/log-in/",
    "title": "Log In"
  },
  "USER_FORGOT_PASSWORD": {
    "name": "USER_FORGOT_PASSWORD",
    "path": "/forgot-password/",
    "title": "Forgot password"
  },
  "USER_RESET_PASSWORD": {
    "name": "USER_RESET_PASSWORD",
    "path": "/reset-password/:token",
    "title": "Reset password"
  },
  "USER_EDIT_ACCOUNT": {
    "name": "USER_EDIT_ACCOUNT",
    "path": "/edit-account/",
    "title": "Edit Account"
  },
  "ACTIVATE_ACCOUNT": {
    "name": "ACTIVATE_ACCOUNT",
    "path": "/activate-account/:token",
    "title": "Activate account"
  }
}
/* eslint-enable */
