
import { ROUTES } from './routes'

export const DEFAULT_LANDING_PAGE = ROUTES.USER_LOG_IN
export const DEFAULT_AUTHENTICATED_PAGE = ROUTES.BRAIN_MAP_MANAGER
export const DEFAULT_UNAUTHENTICATED_PAGE = ROUTES.USER_LOG_IN
export const  UNAUTHENTICATED_PAGE = ROUTES.RESEARCH_BRAIN_MAP_MANAGER
// export const DEFAULT_PRIVACY_POLICY_PAGE = ROUTES.PRIVACY_POLICY