// THIS FILE IS AUTOMATICALLY GENERATED!
// See: runscripts/extract-scss-variables.js

/* eslint-disable */
module.exports = {
  "colorWhite": "rgb(255, 255, 255)",
  "colorWhiteTransparent": "rgba(255, 255, 255, 0.2)",
  "colorBlack": "rgb(0, 0, 0)",
  "colorBlackTransparent": "rgba(10, 12, 17, 0.9)",
  "colorGhost": "rgb(189, 194, 205)",
  "colorGhostTransparent": "rgba(189, 194, 205, 0.2)",
  "colorShark": "rgb(37, 39, 46)",
  "colorMirage": "rgb(27, 32, 43)",
  "colorEbonyClay": "rgb(39, 45, 61)",
  "colorDodgerBlue": "rgb(13, 161, 251)",
  "colorRedAlert": "rgb(252, 38, 41)",
  "colorRedAlertTransparent": "rgba(252, 38, 41, 0.2)",
  "colorButtercup": "rgb(251, 151, 13)",
  "colorLima": "rgb(34, 229, 87)",
  "colorLimaTransparent": "rgba(34, 229, 87, 0.2)",
  "colorGradientRedYellowGreen": "linear-gradient(to right, #e00000 0%, #f7ff00 50%, #3bcf00 100%)",
  "colorBackground": "rgb(27, 32, 43)",
  "colorText": "rgb(255, 255, 255)",
  "colorUi": {
    "white": "rgb(255, 255, 255)",
    "whiteTransparent": "rgba(255, 255, 255, 0.2)",
    "black": "rgb(0, 0, 0)",
    "ghost": "rgb(189, 194, 205)",
    "ghostTransparent": "rgba(189, 194, 205, 0.2)",
    "shark": "rgb(37, 39, 46)",
    "mirage": "rgb(27, 32, 43)",
    "ebonyClay": "rgb(39, 45, 61)",
    "dodgerBlue": "rgb(13, 161, 251)",
    "redAlert": "rgb(252, 38, 41)",
    "redAlertTransparent": "rgba(252, 38, 41, 0.2)",
    "buttercup": "rgb(251, 151, 13)",
    "lima": "rgb(34, 229, 87)",
    "limaTransparent": "rgba(34, 229, 87, 0.2)",
     'border-abbey' : "#51525C",
  },
  "globalRadius": 2,
  "globalTransition": "all 0.3s ease",
  "mqResponsive": true,
  "mqBreakpoints": {
    "mobile": 420,
    "tablet": 600,
    "laptop": 1280,
    "desktop": 1600,
    "ultra": 1920
  },
  "mqShowBreakpoints": "'mobile', 'tablet', 'laptop', 'desktop', 'ultra'",
  "stackIndex": {
    "popup": 3,
    "navigation": 2,
    "pageOverlay": 1,
    "pageContainer": 0
  },
  "fontStackSourceSansPro": "'Source Sans Pro', 'Arial', 'Helvetica Neue', 'Helvetica', sans-serif",
  "fontWeightNormal": 400,
  "fontWeightSemiBold": 600,
  "fontWeightBold": 700,
  "fontHeadings": "'Source Sans Pro', 'Arial', 'Helvetica Neue', 'Helvetica', sans-serif",
  "fontCopy": "'Source Sans Pro', 'Arial', 'Helvetica Neue', 'Helvetica', sans-serif",
  "inuitFractions": "1 2 3 4 5 6 7 8",
  "inuitWrapperWidth": 1120
}
/* eslint-enable */
