
export const brainMapModel = {
  id: null,
  error: null,
  age: null,
  GBM: null,
  name: null,
  slug: null,
  brainMapNotes: null,
  brainMapClassification: null,
  glioma: null,
  patientAmount: null,
  sharedBrainMap: false,
  isResearch: true,
  folderId: null,
  surgicalComplexity: null,
  uploadDate: null,
  mriDate: null,
  lowResBrainMap: {
    registeredT1cAtlasFileURL: null,
    registeredAtlasT1cFileURL: null,
    registeredAtlasT1wFileURL: null,
    registeredAtlasT2wFileURL: null,
    registeredAtlasFlairFileURL: null,
    segmentationFileURL: null,
    probabilityMapFileURL: null,
    binaryMapFileURL: null,
    transformedAtlasFileURL: null,
    transformedSegmentationFileURL: null,
    nrOfPatientsFileURL: null
  },
  highResBrainMap: null,
  sliceFileUrl: null,
  thumbNailSliceFileURL: null
}

export const brainMapFolderModel = {
  id: null,
  name: null
}

export const brainMapModelMock = {
  'brain-maps': [
    {
      id: 'h93JdepU3djfekI',
      age: 51,
      GBM: 'GBM preop',
      name: 'Comparing quality GBM L',
      slug: 'comparing-quality-gbm-l',
      brainMapNotes: 'lorem ipsum',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: true,
      folderId: 1,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      lowResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii'
    },
    {
      id: 'h93Jdep33dzjfekI',
      age: 51,
      GBM: 'GBM preop',
      name: 'Comparing quality GBM R',
      slug: 'comparing-quality-gbm-r',
      brainMapNotes: 'lorem ipsum dolar',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: true,
      folderId: 1,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      lowResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/1/brain-thumbnail.png'
    },
    {
      id: 'h93Jdepd33djfekI',
      age: 51,
      GBM: 'GBM preop',
      name: 'Comparing quality GBM R',
      slug: 'comparing-quality-gbm-r',
      brainMapNotes: 'lorem ipsum sit',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: true,
      folderId: 1,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      lowResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/1/brain-thumbnail.png'
    },
    {
      id: 'h93Jdep33djafekI',
      age: 51,
      GBM: 'GBM preop',
      name: 'Comparing quality GBM R',
      slug: 'comparing-quality-gbm-r',
      brainMapNotes: 'lorem ipsum amet',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: true,
      folderId: 1,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      lowResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/1/brain-thumbnail.png'
    },
    {
      id: 'h93Jdep33dffekI',
      age: 51,
      GBM: 'GBM preop',
      name: 'Comparing quality GBM R',
      slug: 'comparing-quality-gbm-r',
      brainMapNotes: 'lorem ipsum bla',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: true,
      folderId: 2,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      lowResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/4/brain-thumbnail.png'
    },
    {
      id: 'h93Jdefs3djfeew',
      age: 51,
      GBM: 'GBM preop',
      name: 'transforms probability map',
      slug: 'transforms-probability-map',
      brainMapNotes: 'lorem ipsum haha',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: false,
      folderId: 3,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/mock-data/transforms_probability_map.nii',
      lowResBrainMapFileURL: '/mock-data/transforms_probability_map.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/3/brain-thumbnail.png'
    },
    {
      id: 'h93Jdefs3djfekI',
      age: 51,
      GBM: 'GBM preop',
      name: 'blablba',
      slug: 'comparing-quality-gbm-u',
      brainMapNotes: 'lorem ipsum haha',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: false,
      folderId: 3,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      lowResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/3/brain-thumbnail.png'
    },
    {
      id: 'h33JdepU3djfekI',
      age: 51,
      GBM: 'GBM preop',
      name: 'Comparing quality GBM R',
      slug: 'comparing-quality-gbm-r',
      brainMapNotes: 'lorem ipsum tralaa',
      brainMapClassification: 'T1-weighted imaging',
      glioma: '0.45 x 1.34 x 3.01',
      patientAmount: 2,
      sharedBrainMap: true,
      isResearch: false,
      folderId: 3,
      surgicalComplexity: 0.67,
      uploadDate: '2018-10-02',
      mriDate: '2018-09-21',
      highResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      lowResBrainMapFileURL: '/brain-volumes/1/Comparing_quality_GBM_L.nii',
      sliceFileUrl: '/brain-volumes/1/brain-thumbnail.png',
      thumbNailSliceFileURL: '/brain-volumes/2/brain-thumbnail.png'
    }
  ],
  folders: [
    {
      id: 1,
      name: 'Comparing quality GBM L'
    },
    {
      id: 2,
      name: 'Comparing quality GBM R'
    },
    {
      id: 3,
      name: 'My MRI Maps'
    }
  ]
}
